# -*- coding: utf-8 -*-
"""Copy of multiclassanimal.pro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7bYioM85zj8xBZDXCU6wAHP-lCWNQ6E
"""



import kagglehub

# Download latest version
path = kagglehub.dataset_download("iamsouravbanerjee/animal-image-dataset-90-different-animals")

print("Path to dataset files:", path)



#importing neccessary libraries
import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report

#Ensuring the gpu is being used
physical_devices = tf.config.experimental.list_physical_devices('GPU')
if len(physical_devices) > 0:
   tf.config.experimental.set_memory_growth(physical_devices[0], True)
else:
  print("No GPU available")

#PATH TO THE DATASET
dataset_path = "/kaggle/input/animal-image-dataset-90-different-animals/animals/animals"

#list all the classes(animal types)
classes = os.listdir(dataset_path)
num_classes = len(classes)

#display the number of classes along with numbers
print(f"Number of classes:{num_classes}")
print(f"classes:{classes}")

#visualize some sample images from the dataset
plt.figure(figsize=(15,10))
for i, class_name in enumerate(classes[:10]):
   class_path = os.path.join(dataset_path, class_name)
   img_name = os.listdir(class_path)[0]
   img_path = os.path.join(class_path, img_name)
   img = plt.imread(img_path)

   plt.subplot(2, 5, i+1)
   plt.imshow(img)
   plt.title(f'{class_name} \n shape: {img.shape}')
   plt.axis('off')
   plt.tight_layout